apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    {{- if .Values.https_redirect_port }}
    port: "{{ .Values.https_redirect_port }}"
    {{- else }}
    port: "443"
    {{- end }}
    permanent: true
