apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: buffering
  namespace: {{ .Values.namespace }}
spec:
  buffering:
    maxRequestBodyBytes: 524288000 # 500Mo
    maxResponseBodyBytes: 0
