apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-cm
  namespace: {{ .Values.namespace }}
data:
  RAILS_ENV: "{{ .Values.ENV.rails_env }}"
  CLUE_OVERRIDE: "{{ .Values.ENV.clue_override }}"
  SECRET_KEY_BASE: "{{ .Values.ENV.secret_key_base }}"
  MAIL_SMTP_ADDRESS: "{{ .Values.ENV.mail_smtp_address }}"
  MAIL_SMTP_AUTH: "{{ .Values.ENV.mail_smtp_auth }}"
  MAIL_SMTP_USERNAME: "{{ .Values.ENV.mail_smtp_username }}"
  MAIL_SMTP_PASSWORD: "{{ .Values.ENV.mail_smtp_password }}"
  MAIL_SMTP_PORT: "{{ .Values.ENV.mail_smtp_port }}"
  MAIL_SMTP_DOMAIN: "{{ .Values.ENV.mail_smtp_domain }}"
  MAIL_SENDER: "{{ .Values.ENV.mail_sender }}"
  POSTGRES_DB: "{{ .Values.ENV.postgres_db }}"
  POSTGRES_HOST: {{ .Values.db_name }}-svc
  POSTGRES_USER: "{{ .Values.ENV.postgres_user }}"
  POSTGRES_PASSWORD: "{{ .Values.ENV.postgres_password }}"
  POSTGRES_PORT: "{{ .Values.ENV.postgres_port }}"
  DOC_BASE_URL: "{{ .Values.ENV.doc_base_url }}"
  AHOY_ENABLE_TRACKING: "{{ .Values.ENV.ahoy_enable_tracking }}"
  AHOY_VISITS_VALIDITY: "{{ .Values.ENV.ahoy_visits_validity }}"
  AHOY_EVENTS_VALIDITY: "{{ .Values.ENV.ahoy_events_validity }}"
  ENTRY_LOGS_VALIDITY: "{{ .Values.ENV.entry_logs_validity }}"
  API_LOGS_VALIDITY: "{{ .Values.ENV.api_logs_validity }}"
  MAINTENANCE_MODE: "{{ .Values.ENV.maintenance_mode }}"
  MAINTAINER_IPS: "{{ .Values.ENV.maintainer_ips }}"
  REDIS_HOST: "{{ .Values.cache_name }}-svc"
  REDIS_PORT: "{{ .Values.ENV.redis_port }}"
  REDIS_DB: "{{ .Values.ENV.redis_db }}"
  ASSET_HOST: "{{ .Values.ENV.asset_host }}"
  DOMAIN: "{{ .Values.ENV.domain }}"
  PROTOCOL: "{{ .Values.ENV.protocol }}"
  BUGSNAG_API_KEY: "{{ .Values.ENV.bugsnag_api_key }}"
  BUGSNAG_APP_VERSION: "{{ .Values.app_image_tag }}"
  RECAPTCHA_SITE_KEY: "{{ .Values.ENV.recaptcha_site_key }}"
  RECAPTCHA_SECRET_KEY: "{{ .Values.ENV.recaptcha_secret_key }}"
  DEVISE_JWT_SECRET_KEY: "{{ .Values.ENV.devise_jwt_secret_key }}"
  FILE_MAX_UPLOAD_SIZE: "{{ .Values.ENV.file_max_upload_size }}"
  IMAGE_MAX_UPLOAD_SIZE: "{{ .Values.ENV.image_max_upload_size }}"
  EXPORTS_VALIDITY: "{{ .Values.ENV.exports_validity }}"
  ZOOM_LEVEL_DISTANT: "{{ .Values.ENV.zoom_level_distant }}"
  ZOOM_LEVEL_MEDIUM: "{{ .Values.ENV.zoom_level_medium }}"
  ZOOM_LEVEL_CLOSE: "{{ .Values.ENV.zoom_level_close }}"
  POLYGON_COLOR: "{{ .Values.ENV.polygon_color }}"
  POLYLINE_COLOR: "{{ .Values.ENV.polyline_color }}"
  AUTH_FACEBOOK_APP_ID: "{{ .Values.ENV.auth_facebook_app_id }}"
  AUTH_FACEBOOK_APP_SECRET: "{{ .Values.ENV.auth_facebook_app_secret }}"
  AUTH_GITHUB_APP_ID: "{{ .Values.ENV.auth_github_app_id }}"
  AUTH_GITHUB_APP_SECRET: "{{ .Values.ENV.auth_github_app_secret }}"
  AUTH_SHIB_SESSION_ID: "{{ .Values.ENV.auth_shib_session_id }}"
  AUTH_SHIB_APP_ID: "{{ .Values.ENV.auth_shib_app_id }}"
  AUTH_SHIB_NAME: "{{ .Values.ENV.auth_shib_name }}"
  APP_VERSION: "{{ .Values.app_image_tag }}"
